// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIPqvN6CNs1BNm9Wze1PpafqP8EGz85xk',
    appId: '1:344369674208:web:c5fc9bf9c0b745e1745d85',
    messagingSenderId: '344369674208',
    projectId: 'mbbe-id',
    authDomain: 'mbbe-id.firebaseapp.com',
    databaseURL:
        'https://mbbe-id-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mbbe-id.appspot.com',
    measurementId: 'G-1GJ4HC3LY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAblgjoGvH5EvvKEu3crjafwjH_Cd6_uis',
    appId: '1:344369674208:android:7a4bae2922a33b1e745d85',
    messagingSenderId: '344369674208',
    projectId: 'mbbe-id',
    databaseURL:
        'https://mbbe-id-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mbbe-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGlI3cjzVUoxFVh1dWHFY8_k5UQdPOPPU',
    appId: '1:344369674208:ios:705adb5d3f08d214745d85',
    messagingSenderId: '344369674208',
    projectId: 'mbbe-id',
    databaseURL:
        'https://mbbe-id-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mbbe-id.appspot.com',
    iosBundleId: 'org.mbbe.id.mbbeId',
  );
}
